<?php

/**
 * Implementation of hook_uninstall()
 *
 * Cleans up own variables from the system
 */
function fancy_login_uninstall()
{
	variable_del('screen_fade_color');
	variable_del('login_box_height');
	variable_del('login_box_width');
	variable_del('login_box_background_color');
	variable_del('login_box_text_color');
	variable_del('login_box_border_color');
	variable_del('login_box_border_width');
	variable_del('login_box_border_style');
}